# Generated by Django 6.0.3 on 2026-03-11 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savingsdeposit',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='savingsdeposit',
            name='is_auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='auto_tag',
            field=models.CharField(blank=True, help_text='Marks auto-generated entries to prevent duplicates', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_salary_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='salary_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly (1st of each month)'), ('semi', 'Semi-monthly (1st & 16th)')], default='monthly', max_length=10),
        ),
        migrations.CreateModel(
            name='AutoSavingsPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('semi', 'Semi-monthly (1st & 16th)'), ('monthly', 'Monthly (1st of month)')], default='monthly', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_plans', to='page.savingsgoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_savings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(default='Other', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly (1st of month)'), ('semi', 'Semi-monthly (1st & 16th)')], default='monthly', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
